// Code generated by hertz generator.

package api

import (
	"context"

	api "go-web/api/biz/model/api"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateUser .
// @router /v2/user/register [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CreateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CreateUserResponse)

	resp.BaseResp = new(api.BaseResp)
	resp.BaseResp.Code = 0
	resp.BaseResp.Message = "success"

	c.JSON(consts.StatusOK, resp)
}

// CheckUser .
// @router /v2/user/login [POST]
func CheckUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CheckUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CreateUserResponse)

	resp.BaseResp = new(api.BaseResp)
	resp.BaseResp.Code = 0
	resp.BaseResp.Message = "success"

	c.JSON(consts.StatusOK, resp)
}
