// Code generated by hertz generator.

package main

import (
	"go-web/api/biz/rpc"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	rpc.Init()
	// mw.InitJWT()

	// hlog init
	// hlog.SetLogger(hertzlogrus.NewLogger())
	// hlog.SetLevel(hlog.LevelInfo)
}

func main() {
	Init()
	h := server.New(
		server.WithHostPorts(":8080"),
		server.WithHandleMethodNotAllowed(true), // coordinate with NoMethod
	)

	register(h)
	h.Spin()
}
