// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	// rpc.Init()
	// mw.InitJWT()

	// hlog init
	// hlog.SetLogger(hertzlogrus.NewLogger())
	// hlog.SetLevel(hlog.LevelInfo)
}

func main() {
	Init()
	h := server.Default()

	register(h)
	h.Spin()
}
